---
version: '2'
services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule @daily
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@hierophant.localdomain
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=root@hierophant.localdomain
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=hierophant.localdomain
    restart: always
