---
version: '2.2'
services:
  unifi:
    image: jacobalberty/unifi:stable
    container_name: unifi
    init: true
    environment:
      - TZ=America/New_York
      - RUNAS_UID0=false
    ports:
        # Device command/control
      - 8080:8080/tcp
        # Web interface + API
      - 8443:8443/tcp
        # HTTPS portal
      - 8843:8843/tcp
        # HTTP portal
      - 8880:8880/tcp
        # STUN service
      - 3478:3478/udp
        # Speed Test (unifi5 only)
      - 6789:6789/tcp
        # UBNT Discovery
      - 10001:10001/udp
    volumes:
      - unifi:/unifi
    restart: always

volumes:
  unifi:
